queue:
  name: Hosted VS2017
  demands: msbuild

variables:
  "Parameters.solution": MSBuildLocator.sln
  BuildConfiguration: Release
  SignType: Test
  BuildPlatform: ''

steps:
- task: MSBuild@1
  displayName: /t:Pack
  inputs:
    solution: MSBuildLocator.sln
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
    msbuildArguments: '/t:Pack /restore'
    createLogFile: true

- task: CopyFiles@2
  displayName: Collect Symbols
  inputs:
    SourceFolder: 'src/MSBuildLocator'
    Contents: '**\*.pdb'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/symbols'
    CleanTargetFolder: true

- task: PublishBuildArtifacts@1
  displayName: Upload Symbols Artifact
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/symbols'
    ArtifactName: Symbols
    ArtifactType: Container

- task: CopyPublishBuildArtifacts@1
  displayName: Upload Bin to drop
  inputs:
    Contents: |
     src\MSBuildLocator\bin\**
    ArtifactName: bin
    ArtifactType: Container

- task: CopyPublishBuildArtifacts@1
  displayName: Upload NuGet to drop
  inputs:
    Contents: |
     src\MSBuildLocator\bin\$(BuildConfiguration)\*.nupkg
    ArtifactName: pkg
    ArtifactType: Container

- task: CopyPublishBuildArtifacts@1
  displayName: Upload logs to drop
  inputs:
    Contents: '**\*.log'
    ArtifactName: logs
    ArtifactType: Container
  condition: succeededOrFailed()
