trigger: none

resources:
  pipelines:
  - pipeline: microsoft_MSBuildLocator
    source: microsoft.MSBuildLocator
    trigger:
      enabled: false
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

variables:
  SymbolsFeatureName: 'MSBuild'
  SymbolsProject: 'DDE'
  TeamName: 'msbuild'
  VstsDropNames: 'Products/DevDiv/Microsoft/msbuild/$(Build.SourceBranchName)/$(Build.BuildNumber)/$(Build.BuildId)'

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    settings:
      networkIsolationPolicy: Permissive,CFSClean
    pool:
      name: VSEngSS-MicroBuild2022-1ES  
    stages:
    - stage: RetainBuild
      displayName: 'Retain build'
      jobs:
      - job: RetainBuildJob
        displayName: 'Run on agent'
        steps:
        - download: microsoft_MSBuildLocator
          displayName: 'Download Symbols Artifact'
          artifact: Symbols

        - task: MicroBuildArchiveSymbols@6
          displayName: 'Archive $(SymbolsFeatureName) on Symweb'
          inputs:
            SymbolsFeatureName: '$(SymbolsFeatureName)'
            SymbolsProject: '$(SymbolsProject)'
            SymbolsAgentPath: '$(Pipeline.Workspace)/microsoft_MSBuildLocator/Symbols'
            SubmitToInternet: true
            ExpirationInDays: '5475'
            azureSubscription: 'VSEng-SymbolsUpload'
          env:
            SYSTEM_ACCESSTOKEN: $(System.AccessToken)

        - task: MicroBuildRetainVstsDrops@1
          displayName: 'Retain VSTS Drops'
          enabled: false
          inputs:
            DropNames: '$(VstsDropNames)'
            DropServiceUri: 'https://devdiv.artifacts.visualstudio.com/DefaultCollection'

    - stage: PublicRelease
      displayName: 'Public release'
      dependsOn: RetainBuild
      condition: succeeded()
      jobs:
      - job: PushToNuGet
        displayName: 'Push to nuget.org'
        steps:
        - download: microsoft_MSBuildLocator
          displayName: 'Download NuGet Package Artifact'
          artifact: pkg
        - task: 1ES.PublishNuget@1
          displayName: 'NuGet push'
          inputs:
            packageParentPath: '$(Pipeline.Workspace)'
            packagesToPush: '$(Pipeline.Workspace)/microsoft_MSBuildLocator/pkg/Microsoft.Build.Locator*.nupkg'
            nuGetFeedType: 'external'
            publishFeedCredentials: 'MSBuild-Locator'
